module.exports = {
  NOT_FOUND: '데이터를 찾을 수 없습니다.',
  MISSING_REQUIRED_PARAMS: '파라미터를 찾을 수 없습니다.',
  BAD_REQUEST: '잘못된 요청',
  EMPTY_TOKEN: '토큰이 존재하지 않습니다.',
  EXPIRED_TOKEN: '사용자 정보가 만료되었습니다. 다시 로그인해주세요.',
  INVALID_TOKEN: '사용자 정보가 일치하지 않습니다. 다시 로그인해주세요.',
  FAILED_TO_SAVE: '등록에 실패하였습니다.',
  FAILED_TO_EDIT: '수정에 실패하였습니다.',
  FAILED_TO_DELETE: '삭제에 실패하였습니다.',
  FAILED_TO_COPY: '복사에 실패하였습니다.',
  APPLY_SYS: '시스템관리자가 등록되었습니다.',
  DEL_OPER: '운영관리자가 삭제되었습니다.',
  SEND_MAIL_SYS: '인증 코드가 발송되었습니다.',
  NOT_MATCH_CODE: '인증코드가 일치하지 않습니다.',
  NOT_INPUT_CODE: '인증코드가 입력되지 않았습니다.',
  SEND_MAIL: '인증 메일이 발송되었습니다.',
  SEND_MAIL_FAIL: '메일 전송에 실패했습니다.',
  NOT_SYS: '시스템 관리자가 아닙니다.',
  NOT_OPER: '운영 관리자가 아닙니다.',
  NOT_USER: '사용자가 아닙니다.',
  NOT_FOUND_EMAIL: '이메일이 존재하지 않습니다.',
  NOT_FOUND_SYS: '시스템관리자 정보가 존재하지 않습니다.',
  NOT_FOUND_OPER: '등록된 운영관리자가 존재하지 않습니다.',
  NOT_APPROVED_OPER: '시스템관리자 승인이 완료되지 않았습니다.',
  POST_NOT_FOUND: '게시물이 존재하지 않습니다.',
  APPROVED: '승인되었습니다.',
  ALREADY_APPROVED: '이미 승인되었습니다.',
  APPROVED_MAIL: '메일확인이 완료되었습니다.',
  LOCK_DURATION: '인증코드를 5회 이상 잘못입력하여 로그인 제한 상태입니다. \n 10분 후 다시 시도해주세요.',
  RESEND_AUTH: '유효시간이 초과되었습니다. 인증코드를 재발송 해주세요.',
  LOGOUT: '로그아웃 되었습니다.',
  WRONG_APPROACH: '잘못된 접근입니다.',
  RESERVE: '예약되었습니다.',
  DELETE_RESERVE: '예약 취소되었습니다.',
  ALREADY_RESERVE: '이미 예약되었습니다.',
  NOT_FOUND_RESERVE: '예약 정보가 존재하지 않습니다.',
  NOT_USED_ACCOUNT: '교체된 지갑계정 입니다. \n 교체된 지갑계정은 로그인이 불가능합니다.',
  NOT_SUBSTITUTE_ACCOUNT: '교체가 불가능한 \n 지갑계정 입니다.',
}